sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install flake8 pylint bluepy
language: python
script:
- flake8 switchbot --max-line-length=120
- pylint switchbot --max-line-length=120
